name: Trigger Rocky Linux 9 MariaDB 10.6 Workflow

on:
  workflow_dispatch:
    branches: [130.00beta01]
  push:
    branches:
      - 130.00beta01
    paths-ignore:
      - '.gitignore'
      - 'readme.txt'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/main.yml'
      - '.github/workflows/cmm-centos7.yml'
      - '.github/workflows/cmm-almalinux9.yml'
      - '.github/workflows/cmm-rockylinux9.yml'
      - '.github/workflows/cmm-rockylinux8.yml'
      - '.github/workflows/cmm-oraclelinux8.yml'
      - '.github/workflows/cmm-rockylinux8-edge.yml'
      - '.github/workflows/cmm-almalinux8-edge.yml'
      - '.github/workflows/cmm-rockylinux8-php7.4.yml'
      - '.github/workflows/cmm-almalinux8-php7.4.yml'
      - '.github/workflows/cmm-rockylinux8-php8.1.yml'
      - '.github/workflows/cmm-almalinux8-php8.1.yml'
      - '.github/workflows/cmm-rockylinux8-php8.2.yml'
      - '.github/workflows/cmm-almalinux8-php8.2.yml'
      - '.github/workflows/cmm-almalinux9-mariadb10.6.yml'
      - '.github/workflows/cmm-rockylinux9-mariadb10.6.yml'
      - '.github/workflows/cmm-almalinux8-mariadb10.6.yml'
      - '.github/workflows/cmm-rockylinux8-mariadb10.6.yml'
      - '.github/workflows/cmm-almalinux8-mariadb10.4.yml'
      - '.github/workflows/cmm-rockylinux8-mariadb10.4.yml'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger centminmod-workflows workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: centminmod/centminmod-workflows
          event-type: run-rockylinux-9-mariadb-10.6-workflow
